#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# The six packages, platforms first and the wrapper LAST — the same order the CI job publishes in, and
# for the same reason: npm has no transaction across packages, so the one `npx` actually names goes last.
PLATFORM_PKGS=(
  jdwp-mcp-linux-x64
  jdwp-mcp-linux-arm64
  jdwp-mcp-darwin-arm64
  jdwp-mcp-darwin-x64
  jdwp-mcp-windows-x64
)
WRAPPER_PKG=jdwp-mcp
GH_REPO="YgorPerez/java-debugging-mcp"
WORKFLOW_FILE="release.yml"

# slice|package|binary — the release asset name is the interface (docs/toolkit-contract.md), so these
# are not free to rename here.
SLICES=(
  "linux-x86_64|jdwp-mcp-linux-x64|jdwp-mcp"
  "linux-aarch64|jdwp-mcp-linux-arm64|jdwp-mcp"
  "macos-aarch64|jdwp-mcp-darwin-arm64|jdwp-mcp"
  "macos-x86_64|jdwp-mcp-darwin-x64|jdwp-mcp"
  "windows-x86_64|jdwp-mcp-windows-x64|jdwp-mcp.exe"
)

cd "$(dirname "$0")/.."
REPO_ROOT="$PWD"
STAGING=""

# already_published PKG VERSION — true when that exact version is on the registry.
#
# What makes a re-run safe. A published version can never be replaced, so a second attempt must SKIP what
# already landed rather than fail on it: the first real run of this wizard died on package 1 of 5 with a
# 2FA 403, and a wizard that cannot be resumed after a partial failure is a wizard you cannot use.
already_published() {
  local code
  code=$(curl -s -o /dev/null -w '%{http_code}' "https://registry.npmjs.org/$1/$2")
  [[ "$code" == "200" ]]
}

# publish_one PKG — publish one package directory, with a fresh 2FA one-time password.
#
# NPM'S OUTPUT IS STREAMED, NOT CAPTURED, AND THAT IS A BUG FIX RATHER THAN A STYLE CHOICE.
# This used to be `out=$( … npm publish … 2>&1 )`. A command substitution buffers everything until the
# process exits, and npm answers a publish it will not accept by starting a BROWSER flow: it prints an
# auth URL and waits for the round trip. Captured, the URL is invisible until after the failure and the
# wait cannot complete, so every attempt failed the same way with the real error — `code EOTP` — buried
# six lines up in a buffer that was then truncated to `tail -6`. Three runs and two wrong diagnoses came
# out of that on v0.22.0: the visible symptom said "authenticate in your browser", so the account looked
# logged out when it was not. A publish is interactive; let the human see it happen.
#
# WHAT NPM ACTUALLY REQUIRES HERE, measured on v0.22.0 against npm 11.17.0. All three local paths were
# refused with `EOTP`: a web `npm login` session (`npm whoami` answered correctly), an `--otp` code, and
# an access token. Meanwhile the SAME publish succeeded from CI for the three packages that have a
# trusted publisher, with a provenance statement. So on this account a laptop cannot publish at all and
# OIDC is the only path that works — which is what stage 6 exists to set up, and the reason this wizard
# should be a bootstrap nobody needs twice.
publish_one() {
  local pkg="$1" version="$2" out status log
  if already_published "$pkg" "$version"; then
    note "$pkg@$version is already on npm — skipping (a version cannot be republished)"
    return 0
  fi
  say ""
  step "npm publish $pkg@$version"
  local -a otp_arg=()
  if [[ "${TOKEN_AUTH:-0}" == "1" ]]; then
    note "authenticating with NPM_TOKEN"
  else
    # Blank is the RIGHT answer on a security key, not a fallback: WebAuthn is a browser round trip npm
    # starts on its own, and passing --otp with it sends a code npm never asked for.
    ask_secret NPM_OTP "6-digit code from your authenticator (BLANK if you use a security key):"
    [[ -n "${NPM_OTP:-}" ]] && otp_arg=(--otp "$NPM_OTP")
  fi
  log="$(mktemp)"
  # `set +e` around the pipeline, so a refusal is a return value rather than an exit, and PIPESTATUS is
  # read before anything else can clobber it.
  set +e
  ( cd "$REPO_ROOT/npm/$pkg" && npm publish --access public ${otp_arg[@]+"${otp_arg[@]}"} 2>&1 ) | tee "$log"
  status=${PIPESTATUS[0]}
  set -e
  out="$(cat "$log")"; rm -f "$log"
  NPM_OTP=""
  if [[ "$status" -eq 0 ]]; then
    note "published $pkg@$version"
    return 0
  fi
  if printf '%s' "$out" | grep -q "spam detection"; then
    warn "npm refused the NAME, not the credential — and this is the one failure re-running cannot fix."
    say  "Everything else worked: you authenticated, the tarball is real, and the sibling packages go"
    say  "out on the same account. Only npm support can clear the heuristic:"
    step "https://npmjs.com/support — quote the 403 above and this package name"
    say  ""
    say  "Meanwhile nothing is broken for anyone: npm skips an optionalDependencies entry it cannot"
    say  "resolve, so the other platforms install normally and this one gets the shim's message and"
    say  "\`cargo install jdwp-mcp\`, which works on every platform. The wrapper pins $VERSION exactly,"
    say  "so publishing this name later — whenever support clears it — needs no new release."
  elif printf '%s' "$out" | grep -qE "code EOTP|one-time password|Two-factor authentication"; then
    warn "npm wants a second factor and did not get one it could use."
    say  "Which one you need depends on how your account does 2FA, and the two are not interchangeable:"
    step "SECURITY KEY (WebAuthn): npm prints an \`Authenticate your account at: …\` URL and WAITS."
    say  "    Pass NO --otp, run this in a real terminal, and open the URL when it appears. Anything"
    say  "    that captures stdout — a pipe, \$( ), an agent's shell — breaks the wait, and the run then"
    say  "    fails looking like a refusal. That was the whole of v0.22.0's confusion."
    step "AUTHENTICATOR APP (TOTP): the 6-digit code this wizard asks for, entered fresh per package."
    say  ""
    say  "A token does NOT substitute for either: npm restricts 2FA-bypass tokens for publishing, and"
    say  "on v0.22.0 a web session and an access token were refused identically with EOTP."
  fi
  return 1
}

banner "Bootstrap jdwp-mcp on npm"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preconditions"
say "Checking the things that must already be true. Nothing is published in this stage."

# A TTY IS A PRECONDITION, and finding that out at stage 4 is how this reads as a decision it did not make.
# Run through a non-interactive stdin — a pipe, a CI step, an agent's shell, `!` in Claude Code — every
# `pause` returns instantly on EOF and `confirm` sees an empty line, which it correctly treats as "no". The
# run then prints "stopped; nothing was published", which is TRUE and sounds like somebody chose it. Six
# irreversible publishes must not hinge on a prompt nobody could answer, in either direction.
if [[ ! -t 0 ]]; then
  warn "stdin is not a terminal, so the confirmation prompts cannot be answered."
  say  "Every gate here would decline by default and the run would report itself stopped, which reads"
  say  "like a decision rather than a missing keyboard. Run it from a real terminal:"
  say  ""
  say  "    cd $PWD && ./scripts/bootstrap-npm.sh"
  say  ""
  note "Nothing has been published or changed."
  exit 1
fi
for tool in npm node gh jq shasum; do
  if command -v "$tool" >/dev/null 2>&1; then
    note "found $tool"
  elif [[ "$tool" == shasum ]] && command -v sha256sum >/dev/null 2>&1; then
    note "found sha256sum (instead of shasum)"
  else
    warn "$tool is not on PATH"
    die_missing=1
  fi
done
[[ -n "${die_missing:-}" ]] && { warn "install the missing tool(s) and re-run."; exit 1; }

note "Node $(node --version), npm $(npm --version)"
# NOT A GATE, and the distinction cost a correction: npm >= 11.5.1 and Node >= 22.14.0 are what OIDC
# trusted publishing needs, which is the CI job's path. This bootstrap publishes from your login session
# and needs neither, so an older toolchain is reported and allowed rather than refused. Blocking here
# would stop a bootstrap that works fine.
if [[ "$(printf '%s\n11.5.1\n' "$(npm --version)" | sort -V | head -1)" != "11.5.1" ]]; then
  warn "npm $(npm --version) is older than 11.5.1."
  note "That is fine for this bootstrap. It matters only if you ever publish via OIDC by hand;"
  note "the release workflow installs its own pinned npm and checks Node itself."
fi

VERSION=$(jq -r .version "$REPO_ROOT/npm/$WRAPPER_PKG/package.json")
TAG="v$VERSION"
note "the npm manifests in this tree say $VERSION, so this bootstrap publishes $VERSION"

say ""
say "The binaries come from the GitHub release for $TAG — the same artefacts CI would publish, so"
say "the bootstrap and every later automated publish ship identical bytes."
if ! gh release view "$TAG" >/dev/null 2>&1; then
  warn "there is no $TAG release yet."
  say  "Cut it first (scripts/release.sh / the /release command), let the tag build finish, then re-run."
  say  "The publish-npm job in that run WILL fail — that is expected until this wizard has run once."
  exit 1
fi
missing=0
for entry in "${SLICES[@]}"; do
  IFS='|' read -r slice _pkg bin <<<"$entry"
  asset="jdwp-mcp-${TAG}-${slice}"; [[ "$bin" == *.exe ]] && asset="${asset}.exe"
  if gh release view "$TAG" --json assets --jq '.assets[].name' | grep -qx "$asset"; then
    note "  $asset"
  else
    warn "  MISSING: $asset"; missing=1
  fi
done
if (( missing )); then
  warn "the $TAG release does not carry all five binaries."
  say  "Publishing a platform package with no binary would ship a broken version that npm never lets you"
  say  "replace. Fix the release first."
  exit 1
fi
note "all five binaries present"
pause "Preconditions look good. Continue?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Sign in to npm"
say "This is the one credential in the whole procedure."
say ""
say "TWO WAYS IN, and which one you use decides whether the publishes need 2FA codes:"
step "npm login (a browser session) — then each publish needs a fresh 6-digit code, because a web"
say  "    session does not satisfy an account that enforces 2FA for publishing."
step "NPM_TOKEN=… in the environment — a granular or automation token that bypasses 2FA, so no codes."
say ""
note "With NPM_TOKEN the token is written ONLY to a mode-0600 file in a temp dir, used as npm's"
note "user config for this run, and deleted when the wizard exits. It never reaches this repo, never"
note "appears on a command line, and is never echoed."

if [[ -n "${NPM_TOKEN:-}" ]]; then
  NPMRC="$(mktemp)"
  chmod 600 "$NPMRC"
  printf '//registry.npmjs.org/:_authToken=%s\n' "$NPM_TOKEN" > "$NPMRC"
  export NPM_CONFIG_USERCONFIG="$NPMRC"
  trap 'rm -f "$NPMRC"; [[ -n "${STAGING:-}" ]] && rm -rf "$STAGING"' EXIT
  note "using NPM_TOKEN from the environment"
  TOKEN_AUTH=1
elif npm whoami >/dev/null 2>&1; then
  note "already signed in as $(npm whoami)"
  TOKEN_AUTH=0
else
  step "A browser window will open for npm's login flow."
  npm login || { warn "login did not complete"; exit 1; }
  TOKEN_AUTH=0
fi
WHO=$(npm whoami 2>/dev/null || echo "")
[[ -z "$WHO" ]] && { warn "npm does not recognise these credentials — check the token or run npm login."; exit 1; }
note "signed in as $WHO"
if [[ "$WHO" != "ygorperez" ]]; then
  warn "expected ygorperez — you are $WHO."
  confirm "Publish the six packages as $WHO anyway?" || exit 1
fi
pause "Continue?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Stage the release binaries"
say "Downloading the $TAG assets and verifying them against SHA256SUMS, then copying each into its"
say "platform package. Nothing is published yet."
STAGING=$(mktemp -d)
# Extends rather than replaces the stage-2 trap, which may hold an npmrc to delete.
trap 'rm -rf "$STAGING"; [[ -n "${NPMRC:-}" ]] && rm -f "$NPMRC"' EXIT
gh release download "$TAG" --dir "$STAGING" --pattern 'jdwp-mcp-*' --pattern 'SHA256SUMS'
if command -v sha256sum >/dev/null 2>&1; then
  ( cd "$STAGING" && sha256sum --check --ignore-missing SHA256SUMS ) || { warn "checksum mismatch"; exit 1; }
else
  ( cd "$STAGING" && shasum -a 256 --check --ignore-missing SHA256SUMS ) || { warn "checksum mismatch"; exit 1; }
fi
note "checksums verified"
for entry in "${SLICES[@]}"; do
  IFS='|' read -r slice pkg bin <<<"$entry"
  src="$STAGING/jdwp-mcp-${TAG}-${slice}"; [[ "$bin" == *.exe ]] && src="${src}.exe"
  [[ -f "$src" ]] || { warn "$src vanished after download"; exit 1; }
  cp "$src" "$REPO_ROOT/npm/$pkg/$bin"
  chmod +x "$REPO_ROOT/npm/$pkg/$bin"
  note "staged $slice -> npm/$pkg/$bin"
done
say ""
say "These binaries are deliberately NOT committed — they are build output, and the CI job stages them"
say "the same way on every release. Delete them after this run if you like; nothing depends on them."
pause "Continue?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Publish the five platform packages"
warn "THIS IS IRREVERSIBLE. An npm version can be deprecated, but never replaced or re-uploaded."
say ""
say "Publishing $VERSION of:"
for p in "${PLATFORM_PKGS[@]}"; do note "  $p"; done
say ""
say "The wrapper is NOT published here. If one of these fails, nothing installable exists yet —"
say "which is exactly the property that makes a half-finished run safe to abandon."
say ""
if [[ "${TOKEN_AUTH:-0}" == "1" ]]; then
  note "Authenticating with NPM_TOKEN."
else
  note "A code is single-use and lasts about 30 seconds, which is why this asks once per package rather"
  note "than once. Leave it blank if you have no authenticator."
fi
# SAY THE ODDS BEFORE THE IRREVERSIBLE PROMPT, not after the failure. Measured on v0.22.0 against
# npm 11.17.0: a web login session, an `--otp` code and an access token were each refused with `EOTP`,
# while CI published the same artefacts over OIDC. If that is still npm's posture, every publish below
# fails and the useful stage is 6.
warn "npm may refuse a publish from this machine whatever credential you give it."
say  "On v0.22.0 all three local paths — web login, --otp, access token — answered EOTP, while the"
say  "packages with a trusted publisher went out from CI without one. If that happens again, skip to"
say  "stage 6 and let $WORKFLOW_FILE do it: a package that already exists never needs this wizard."
note "Anything already on npm is skipped, so a re-run after a failure resumes rather than repeats."
confirm "Publish these five now?" || { warn "stopped; nothing was published"; exit 1; }
# COLLECTED, NOT ABORTED ON. npm can refuse ONE name for reasons that have nothing to do with the others
# — v0.21.0's `jdwp-mcp-win32-x64` was refused with `403 … Package name triggered spam detection` after the
# other four had published with the same token — and stopping there meant the four that worked were
# unusable, because the wrapper never went out.
#
# THAT `403` WAS NOT THROTTLING. On 2026-08-12 the name became an npm security-holder package owned by
# `npm-support`, so the refusal was npm taking the name rather than rate-limiting the attempt, and the
# Windows package was renamed to `jdwp-mcp-windows-x64` (REL-10, #194). A `403` here can mean the name is
# gone for good; it looks identical to one that will succeed on a retry, so do not assume a retry is the fix.
#
# Publishing a SUBSET is LESS BAD than a half-published wrapper, which is not the same as safe: an
# `optionalDependencies` entry that does not resolve is skipped silently by npm (measured), so that platform
# installs the wrapper and gets NO BINARY. REL-7 (#184) is what that costs when the missing platform is the
# common one — v0.22.0 shipped without linux-x86_64. The shim does tell that caller the truth and points at
# `cargo install`, but a caller reading a shim message has a broken install, not a working subset.
#
# What must not happen is a subset shipping because nobody noticed. So every failure is named, and the
# wrapper needs an explicit yes when the set is incomplete.
FAILED_PKGS=()
for entry in "${SLICES[@]}"; do
  IFS='|' read -r _slice pkg _bin <<<"$entry"
  publish_one "$pkg" "$VERSION" || FAILED_PKGS+=("$pkg")
done

if (( ${#FAILED_PKGS[@]} == ${#PLATFORM_PKGS[@]} )); then
  say ""
  warn "not one platform package published, so there is nothing for a wrapper to point at."
  say  "Fix the cause above and re-run; nothing has been published."
  exit 1
fi

PARTIAL=0
if (( ${#FAILED_PKGS[@]} )); then
  PARTIAL=1
  say ""
  warn "${#FAILED_PKGS[@]} of ${#PLATFORM_PKGS[@]} did not publish: ${FAILED_PKGS[*]}"
  say ""
  say "Publishing the wrapper now ships $(( ${#PLATFORM_PKGS[@]} - ${#FAILED_PKGS[@]} )) of ${#PLATFORM_PKGS[@]} platforms. What that means:"
  step "the platforms that DID publish work completely — npm skips an optional dependency it cannot resolve"
  step "the missing ones get the shim's message naming both causes, and \`cargo install jdwp-mcp\`, which"
  say  "    works on every platform and always has"
  step "the gap closes WITHOUT a new release: the wrapper pins each platform at this exact version, so"
  say  "    publishing the missing package at $VERSION later makes this wrapper find it"
  say ""
  # "NOTHING IS WRONG" IS ONLY TRUE ON A FIRST BOOTSTRAP, so it is checked rather than asserted. Once the
  # wrapper for this version exists — which it does whenever CI got that far and only the platforms failed,
  # the v0.22.0 case — the gap is already live for anyone on the missing platform, and telling someone to
  # calmly stop and fix the cause would be describing a different situation than the one they are in.
  if already_published "$WRAPPER_PKG" "$VERSION"; then
    warn "$WRAPPER_PKG@$VERSION IS ALREADY ON NPM, so stopping does not leave things quiet."
    say  "It pins each platform at exactly $VERSION, so \`npx $WRAPPER_PKG\` on ${FAILED_PKGS[*]} is"
    say  "resolving to nothing RIGHT NOW and falling through to the shim's message. Publishing the"
    say  "missing package is what closes that, and it needs no new release."
  else
    note "The alternative is to stop here, fix the cause, and re-run — the platforms that published are"
    note "inert until a wrapper points at them, so nothing is installable and nothing is wrong yet."
  fi
  confirm "Ship $(( ${#PLATFORM_PKGS[@]} - ${#FAILED_PKGS[@]} )) of ${#PLATFORM_PKGS[@]} platforms?" \
    || { warn "stopped. The published platform packages stay inert until a wrapper points at them."; exit 1; }
else
  note "all ${#PLATFORM_PKGS[@]} platform packages are on npm"
fi
pause "Continue?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Publish the wrapper, last"
warn "ALSO IRREVERSIBLE, and this is the step that makes the set installable."
say ""
if (( PARTIAL )); then
  say "After this, 'npx jdwp-mcp@$VERSION' resolves on the platforms that published, and reports itself"
  say "honestly on: ${FAILED_PKGS[*]}"
else
  say "After this, 'npx jdwp-mcp@$VERSION' resolves and pulls exactly one of the five binaries."
fi
confirm "Publish $WRAPPER_PKG@$VERSION now?" || { warn "stopped; the platform packages are published but inert"; exit 1; }
publish_one "$WRAPPER_PKG" "$VERSION" \
  || { warn "the wrapper did not publish. The five platform packages are up and inert until it does —"; \
       say  "      re-run and they will be skipped."; exit 1; }
pause "Continue?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Enable trusted publishing on all six"
say "This is what stops the next release needing your login — and why this repo stores no npm token."
say "It can only be done now, because a trusted publisher attaches to a package that already exists."
say ""
say "On EACH of the six settings pages, find the 'Trusted Publisher' section, click"
say "'Select your publisher', choose GitHub Actions, and fill in:"
step "Organization or user:  ${GH_REPO%%/*}"
step "Repository:            ${GH_REPO##*/}"
step "Workflow filename:     $WORKFLOW_FILE      (filename only, not a path)"
step "Environment name:      leave blank"
step "Allowed actions:       npm publish"
say ""
note "npm's own reference: https://docs.npmjs.com/trusted-publishers"
pause "Ready to open the first one?"
for p in "${PLATFORM_PKGS[@]}" "$WRAPPER_PKG"; do
  say ""
  open_url "https://www.npmjs.com/package/$p/access"
  pause "Configured the trusted publisher for $p? Press Enter for the next."
done
say ""
say "If npm's UI has moved since this was written, follow the docs link above rather than guessing —"
say "the four values are what matter, wherever the form now lives."
pause "All six configured?"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Verify, and hand back to CI"
say "Checking that the published wrapper actually resolves and starts."
say ""
if printf '%s\n' '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"bootstrap","version":"0"}}}' \
     | npx -y "jdwp-mcp@$VERSION" 2>/dev/null | grep -q '"result"'; then
  note "npx jdwp-mcp@$VERSION answered initialize — the package works end to end"
else
  warn "npx could not start the published package."
  say  "npm's CDN can lag a minute or two after a publish; try again before assuming it is broken:"
  say  "  npx -y jdwp-mcp@$VERSION"
fi
if (( PARTIAL )); then
  say ""
  warn "SHIPPED WITHOUT: ${FAILED_PKGS[*]}"
  say  "Close the gap with no new release, once npm accepts the name:"
  for p in "${FAILED_PKGS[@]}"; do note "  ( cd npm/$p && npm publish --access public )"; done
  note "The wrapper pins $VERSION exactly, so it finds them the moment they exist."
fi
say ""
say "From here the tag workflow does it: the publish-npm job exchanges an OIDC token and publishes all"
say "six, wrapper last. No token is stored anywhere, and this wizard should never need running again."
say ""
note "If you want to leave the tree clean, remove the staged binaries:"
for entry in "${SLICES[@]}"; do
  IFS='|' read -r _slice pkg bin <<<"$entry"
  note "  rm -f npm/$pkg/$bin"
done

finish
